### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Saurabh702**
@sharanvarma0 
Review commits and approve for merge with master,
If changes are required, make necessary commits

### CODE REVIEW

**Review by sharanvarma0 — COMMENTED** [review]
itoa() function does not seem to be working.

**Comment by Saurabh702** [comment]
Things to do:
* Unit tests (test cases)
* Add makefile (related issue : itoa() reference not found)
* Bug: Outputs don't match for input "1\*100-100/100-100\*100"
   Compare Output with bc in bash (probably related to associativity of operators)
* remove setjmp functions if possible
* replacement for gets (warning)

**Review by sharanvarma0 — APPROVED** [review]
I have added the makefile in the develop-patch1 branch. itoa() has been changed to snprintf() function for WORA. the outputs i am not sure. setjmp functions are not causing any issue for now so no need to remove them.

**Comment by Saurabh702** [comment]
@sharanvarma0 
For adding precedence of operators, check part 5 of the blog :
https://ruslanspivak.com/lsbasi-part5/
Also follow part 4 of the blog, which breaks the program into different sections: lexer,parser and interpreter : 
https://ruslanspivak.com/lsbasi-part4/

**Pull request merged**
